# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
<!DOCTYPE html>
<html>
<head>
<style>
table, th, td {
  border: 5px solid black;
  border-collapse: collapse;
}
th, td {
  padding: 5px;
}
</style>
</head>
<body>

<table style="width:60%" align = "center">
  <tr>
    <td>Link to Homework #1 </td>
    <td>Link to Homework #2</td>
  </tr>
  <tr>
    <td><a href= "ScrambleThisName.html">Link to Homework #3</a></td>
    <td><a href= "ScrambleThisName.html">Link to Homework #4</a></td>
  </tr>
  <tr>
    <td>Link to Homework #5</td>
    <td><a href= "ScrambleThisName.html">Link to Homework #6</a></td>
  </tr>
  <tr>
    <td>Link to Homework #7</td>
    <td><a href= "ScrambleThisName.html">Link to Homework #8</a></td>
  </tr>
  <tr>
    <td>Link to Homework #9</td>
    <td>Link to Homework #10</td>
  </tr>
  </table>
</body>
</html>
        
        
        
        
        
        
        
